// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI-is6PB2Hu3jzDMVEuyMwyjyzwI031cQ',
    appId: '1:85675572133:web:8d239b7fe05f0eb4f8064c',
    messagingSenderId: '85675572133',
    projectId: 'bg-medapp',
    authDomain: 'bg-medapp.firebaseapp.com',
    storageBucket: 'bg-medapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS-G6W-7vYn0G1JU79DIVr_Ngf56xXDVs',
    appId: '1:85675572133:android:4fe23b71f86bb65cf8064c',
    messagingSenderId: '85675572133',
    projectId: 'bg-medapp',
    storageBucket: 'bg-medapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu0gB_srob_0Pv-5Ak56h8Qc_kWx2aQCI',
    appId: '1:85675572133:ios:3f5e5a0d17fe2180f8064c',
    messagingSenderId: '85675572133',
    projectId: 'bg-medapp',
    storageBucket: 'bg-medapp.firebasestorage.app',
    iosBundleId: 'com.example.bgMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu0gB_srob_0Pv-5Ak56h8Qc_kWx2aQCI',
    appId: '1:85675572133:ios:3f5e5a0d17fe2180f8064c',
    messagingSenderId: '85675572133',
    projectId: 'bg-medapp',
    storageBucket: 'bg-medapp.firebasestorage.app',
    iosBundleId: 'com.example.bgMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI-is6PB2Hu3jzDMVEuyMwyjyzwI031cQ',
    appId: '1:85675572133:web:bcee4e7b1e75b2f4f8064c',
    messagingSenderId: '85675572133',
    projectId: 'bg-medapp',
    authDomain: 'bg-medapp.firebaseapp.com',
    storageBucket: 'bg-medapp.firebasestorage.app',
  );
}
